# Configuración existente de tu dbt_project.yml
name: 'transform_dbt'
version: '1.0.0'
config-version: 2

profile: 'transform_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  transform_dbt:
    +materialized: table